from datetime import datetime
import os

class BugReporter:
    def __init__(self, target):
        self.target = target
        self.findings = []
        self.report_date = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    def add_finding(self, subdomain, finding):
        # ვუზრუნველყოფთ, რომ PoC ყოველთვის იყოს სრული URL
        poc_link = finding.get('poc', '#')
        if not poc_link.startswith(('http://', 'https://')):
            if ':' in poc_link and not poc_link.startswith('http'):
                poc_link = f"http://{poc_link.split(' ')[-1]}" # პორტებისთვის

        self.findings.append({
            "subdomain": subdomain,
            "type": finding['type'],
            "val": finding['val'],
            "severity": finding.get('severity', 'medium'),
            "poc_link": poc_link
        })

    def generate_html(self):
        filename = f"report_{self.target.replace('.', '_')}.html"
        severity_colors = {"critical": "#ff4d4d", "high": "#ff8533", "medium": "#ffcc00", "low": "#3399ff"}
        
        grouped_findings = {}
        for fn in self.findings:
            category = fn['type']
            if category not in grouped_findings:
                grouped_findings[category] = []
            grouped_findings[category].append(fn)

        html_content = f"""
        <html>
        <head>
            <title>BugHunter AI - {self.target}</title>
            <style>
                body {{ font-family: 'Segoe UI', sans-serif; background: #0a0a0a; color: #d0d0d0; padding: 40px; }}
                .container {{ max-width: 1100px; margin: auto; }}
                .header {{ display: flex; align-items: center; justify-content: space-between; border-bottom: 2px solid #00ff41; padding-bottom: 20px; margin-bottom: 40px; }}
                .header-info h1 {{ color: #fff; margin: 0; }}
                .header-info a {{ color: #00ff41; text-decoration: none; font-weight: bold; }}
                .profile-img {{ width: 65px; height: 65px; border-radius: 50%; border: 2px solid #00ff41; box-shadow: 0 0 10px #00ff41; }}
                .category-title {{ background: #1a1a1a; padding: 10px 20px; border-radius: 5px; margin-top: 30px; border-left: 4px solid #00ff41; color: #00ff41; }}
                .card {{ background: #111; border: 1px solid #222; border-radius: 8px; padding: 15px; margin-bottom: 10px; display: flex; justify-content: space-between; align-items: center; }}
                .severity-critical {{ border-right: 6px solid {severity_colors['critical']}; }}
                .severity-high {{ border-right: 6px solid {severity_colors['high']}; }}
                .btn {{ background: #00ff41; color: #000; padding: 8px 18px; border-radius: 4px; text-decoration: none; font-weight: bold; font-size: 0.85em; }}
                code {{ color: #00ff41; background: #000; padding: 2px 5px; }}
                .footer {{ text-align: center; margin-top: 60px; padding: 20px; border-top: 1px solid #222; font-size: 0.9em; }}
                .footer a {{ color: #00ff41; text-decoration: none; }}
            </style>
        </head>
        <body>
            <div class="container">
                <div class="header">
                    <div class="header-info">
                        <h1>🛡️ BugHunter AI - Audit Report | <a href="https://github.com/1lo1lo1" target="_blank">1lo</a></h1>
                        <p>Target: <code>{self.target}</code> | Date: {self.report_date}</p>
                        <p>Verified Findings: <b>{len(self.findings)}</b></p>
                    </div>
                    <a href="https://github.com/1lo1lo1" target="_blank">
                        <img src="https://avatars.githubusercontent.com/u/161965005?v=4" class="profile-img" alt="1lo">
                    </a>
                </div>
        """

        for category, items in grouped_findings.items():
            html_content += f'<div class="category-title"><h3>{category} ({len(items)})</h3></div>'
            for fn in items:
                html_content += f"""
                <div class="card severity-{fn['severity']}">
                    <div>
                        <b>Host:</b> <code>{fn['subdomain']}</code><br>
                        <small style="color:#888;">Evidence: {fn['val']}</small>
                    </div>
                    <a href="{fn["poc_link"]}" target="_blank" rel="noopener noreferrer" class="btn">View Proof</a>
                </div>
                """
        
        html_content += f"""
                <div class="footer">
                    Generated by <a href="https://github.com/1lo1lo1" target="_blank">BugHunter AI Framework - Penetration Testing Module | 1lo</a>
                </div>
            </div>
        </body>
        </html>
        """
        with open(filename, "w") as f: f.write(html_content)
        return filename
